/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.hardcord;

import vistas.FmPrincipal;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JToggleButton;

/**
 *
 * @author joelvalenzuela
 */
public class Cuate extends javax.swing.JDialog {

//    Platillo platillo;
    ArrayList<JToggleButton> botonesChidori;
//    PlatilloJpaController cPlatillo = new PlatilloJpaController();
    FmPrincipal fmPrincipal;

    /**
     * Creates new form Yaqui
     */
    public Cuate(java.awt.Frame parent, boolean modal, FmPrincipal fmPrincipal) {
        super(parent, modal);
        initComponents();
//        botonesChidori = new ArrayList();
        this.fmPrincipal = fmPrincipal;
        addBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbtnSalchicha = new javax.swing.JToggleButton();
        tbtnTocino = new javax.swing.JToggleButton();
        tbtnCatsup = new javax.swing.JToggleButton();
        tbtnCT = new javax.swing.JToggleButton();
        tbtnPlain = new javax.swing.JToggleButton();
        tbtnMostaza = new javax.swing.JToggleButton();
        tbtnCebolla = new javax.swing.JToggleButton();
        tbtnFrijol = new javax.swing.JToggleButton();
        tbtnTomate = new javax.swing.JToggleButton();
        tbtnCotija = new javax.swing.JToggleButton();
        tbtnSalsaJalapeno = new javax.swing.JToggleButton();
        tbtnGuacamole = new javax.swing.JToggleButton();
        tbtnMayonesa = new javax.swing.JToggleButton();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbtnSalchicha.setText("Salchicha");
        tbtnSalchicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSalchichaActionPerformed(evt);
            }
        });

        tbtnTocino.setText("Tocino");

        tbtnCatsup.setText("Catsup");

        tbtnCT.setText("CT");
        tbtnCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnCTActionPerformed(evt);
            }
        });

        tbtnPlain.setText("Plain");
        tbtnPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPlainActionPerformed(evt);
            }
        });

        tbtnMostaza.setText("Mostaza");

        tbtnCebolla.setText("Cebolla");

        tbtnFrijol.setText("Frijol");

        tbtnTomate.setText("Tomate");

        tbtnCotija.setText("Cotija");

        tbtnSalsaJalapeno.setText("Salsa Jalapeno");

        tbtnGuacamole.setText("Guacamole");

        tbtnMayonesa.setText("Mayonesa");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tbtnCT))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(tbtnCebolla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(tbtnSalchicha))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbtnTocino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbtnPlain)
                            .addComponent(tbtnFrijol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnCatsup)
                            .addComponent(tbtnTomate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbtnMostaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbtnCotija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbtnSalsaJalapeno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnGuacamole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnMayonesa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnCT)
                    .addComponent(tbtnPlain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnSalchicha)
                    .addComponent(tbtnTocino)
                    .addComponent(tbtnCatsup)
                    .addComponent(tbtnMostaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnCebolla)
                    .addComponent(tbtnFrijol)
                    .addComponent(tbtnTomate)
                    .addComponent(tbtnCotija))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnSalsaJalapeno)
                    .addComponent(tbtnGuacamole)
                    .addComponent(tbtnMayonesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnRegresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCTActionPerformed

        tbtnCT.setSelected(true);
        tbtnSalchicha.setSelected(true);
        tbtnTocino.setSelected(true);
        tbtnCatsup.setSelected(true);
        tbtnMostaza.setSelected(true);
        tbtnCebolla.setSelected(true);
        tbtnFrijol.setSelected(true);
        tbtnTomate.setSelected(true);
        tbtnCotija.setSelected(true);
        tbtnSalsaJalapeno.setSelected(true);
        tbtnGuacamole.setSelected(true);
        tbtnMayonesa.setSelected(true);
        tbtnPlain.setSelected(false);
    }//GEN-LAST:event_tbtnCTActionPerformed

    private void tbtnPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPlainActionPerformed
        tbtnCT.setSelected(false);
        tbtnSalchicha.setSelected(true);
        tbtnTocino.setSelected(true);
        tbtnCatsup.setSelected(false);
        tbtnMostaza.setSelected(false);
        tbtnCebolla.setSelected(false);
        tbtnFrijol.setSelected(false);
        tbtnTomate.setSelected(false);
        tbtnCotija.setSelected(false);
        tbtnSalsaJalapeno.setSelected(false);
        tbtnGuacamole.setSelected(false);
        tbtnMayonesa.setSelected(false);
        tbtnPlain.setSelected(true);
    }//GEN-LAST:event_tbtnPlainActionPerformed

    private void tbtnSalchichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSalchichaActionPerformed
        if (tbtnSalchicha.isSelected()) {
            tbtnTocino.setSelected(true);
        } else {
            tbtnTocino.setSelected(false);
        }
    }//GEN-LAST:event_tbtnSalchichaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
//        addIngredientes();
        
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed
//
//    public void addIngredientes() {
//        ArrayList<Ingredientes> ingredientes = new ArrayList<>();
//
//        for (JToggleButton boton : botonesChidori) {
//            if (boton.isSelected()) {
//                if( !boton.getText().equalsIgnoreCase("plain") && !boton.getText().equalsIgnoreCase("ct")){
//                Ingredientes temp = new Ingredientes();
//                temp.setNombre(boton.getText());
//                ingredientes.add(temp);}
//            }
//        }
//         obtenerPlatillo().setIngredientesList(ingredientes);
//         
//        fmPrincipal.getPlatillos().add(platillo);
//        fmPrincipal.notasOrden(platillo);
//
//       
//
//    }
//
//    public Platillo obtenerPlatillo() {
//        List<Platillo> platillos = cPlatillo.findPlatilloEntities();
//        
//
//        for (Platillo platillo1 : platillos) {
//            if (platillo1.getNombre().equalsIgnoreCase("cuate")) {
//                platillo = platillo1;
//                break;
//            }
//        }
//
//        return platillo;
//
//    }

    public void addBotones() {
        botonesChidori.add(tbtnCT);
        botonesChidori.add(tbtnPlain);
        botonesChidori.add(tbtnCatsup);
        botonesChidori.add(tbtnCebolla);
        botonesChidori.add(tbtnCotija);
        botonesChidori.add(tbtnFrijol);
        botonesChidori.add(tbtnGuacamole);
        botonesChidori.add(tbtnMayonesa);
        botonesChidori.add(tbtnMostaza);
        botonesChidori.add(tbtnSalchicha);
        botonesChidori.add(tbtnSalsaJalapeno);
        botonesChidori.add(tbtnTocino);
        botonesChidori.add(tbtnTomate);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Yaqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Yaqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Yaqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Yaqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Yaqui dialog = new Yaqui(new javax.swing.JFrame(), true, fmPrincipal);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JToggleButton tbtnCT;
    private javax.swing.JToggleButton tbtnCatsup;
    private javax.swing.JToggleButton tbtnCebolla;
    private javax.swing.JToggleButton tbtnCotija;
    private javax.swing.JToggleButton tbtnFrijol;
    private javax.swing.JToggleButton tbtnGuacamole;
    private javax.swing.JToggleButton tbtnMayonesa;
    private javax.swing.JToggleButton tbtnMostaza;
    private javax.swing.JToggleButton tbtnPlain;
    private javax.swing.JToggleButton tbtnSalchicha;
    private javax.swing.JToggleButton tbtnSalsaJalapeno;
    private javax.swing.JToggleButton tbtnTocino;
    private javax.swing.JToggleButton tbtnTomate;
    // End of variables declaration//GEN-END:variables
}
