/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Entidades.Ingredientes;
import Entidades.Platillo;
import Entidades.Usuarios;
import fachadaLogica.FachadaIngredientes;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zannie
 */
public class FmAdminIngredientes extends javax.swing.JFrame {

    FmAdminMenu adminMenu;
    DefaultTableModel modelo;
    FachadaIngredientes ingredientes = new FachadaIngredientes();
    Usuarios usuarioActual;

    /**
     * Creates new form FmAdminIngredientes
     */
    public FmAdminIngredientes(Usuarios usuarioActual) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioActual = usuarioActual;
        tamPantalla();
        setIconBotones();
        cargarTabla();
    }

    private FmAdminIngredientes() {
        initComponents();
        setLocationRelativeTo(null);
        tamPantalla();
        setIconBotones();
        cargarTabla();
    }

    public final void tamPantalla() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        this.setSize(width, height);
        setResizable(false);
        pack();
    }

    public final void setIconBotones() {
        btnCancelar.setSize(28, 28);
        btnCancelar.setIcon(setIcono("/images/izquierda.png", btnCancelar));
        btnCancelar.setText("");

    }

    public Icon setIcono(String url, JButton boton) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = (boton.getWidth());
        int largo = (boton.getHeight());
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, largo, Image.SCALE_DEFAULT));

        return icono;
    }

    private DefaultTableModel ingredientesTableModel(List<Ingredientes> lstIngredientes) {
        Object tabla[][];
        String[] nombreCols = {"ID", "Nombre", "Abreviación"};
        if (lstIngredientes != null) {
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tabla = new Object[lstIngredientes.size()][nombreCols.length];
            for (int i = 0; i < lstIngredientes.size(); i++) {
                Ingredientes ingrediente = lstIngredientes.get(i);
                tabla[i][0] = ingrediente.getIdingredientes();
                tabla[i][1] = ingrediente.getNombre();
                tabla[i][2] = ingrediente.getAbreviacion();
            }
            modelo.setDataVector(tabla, nombreCols);
            return modelo;
        }
        return null;
    }

    private void cargarTabla() {
        tablaIngredientes.setModel(ingredientesTableModel(ingredientes.consultarIngredientes()));
    }

    private void limpiarCampos() {
        this.txtId.setText("");
        this.txtNombre.setText("");
        this.txtAbreviacion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCafecito = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblAbreviacion = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngredientes = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtAbreviacion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar ingredientes");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCafecito.setBackground(new java.awt.Color(226, 207, 169));
        pnlCafecito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(245, 133, 25));
        lblTitulo.setText("Administrar Ingredientes");
        pnlCafecito.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        lblId.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(91, 52, 46));
        lblId.setText("ID ");
        pnlCafecito.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 30));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(254, 244, 222));
        pnlCafecito.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 90, 180, -1));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(91, 52, 46));
        lblNombre.setText("Nombre");
        pnlCafecito.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtNombre.setBackground(new java.awt.Color(254, 244, 222));
        pnlCafecito.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 164, 180, -1));

        lblAbreviacion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAbreviacion.setForeground(new java.awt.Color(91, 52, 46));
        lblAbreviacion.setText("Abreviación");
        pnlCafecito.add(lblAbreviacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        panelTabla.setBackground(new java.awt.Color(254, 244, 222));
        panelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(245, 133, 25))); // NOI18N
        panelTabla.setForeground(new java.awt.Color(245, 133, 25));
        panelTabla.setToolTipText("");
        panelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaIngredientes);

        panelTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 401, 293));

        pnlCafecito.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 90, 420, 320));

        btnEliminar.setBackground(new java.awt.Color(245, 133, 25));
        btnEliminar.setForeground(new java.awt.Color(91, 52, 46));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlCafecito.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 412, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(245, 133, 25));
        btnActualizar.setForeground(new java.awt.Color(91, 52, 46));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        pnlCafecito.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 412, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(245, 133, 25));
        btnGuardar.setForeground(new java.awt.Color(91, 52, 46));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlCafecito.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 412, -1, -1));

        txtAbreviacion.setBackground(new java.awt.Color(254, 244, 222));
        pnlCafecito.add(txtAbreviacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 253, 180, -1));

        btnCancelar.setBackground(new java.awt.Color(254, 244, 222));
        btnCancelar.setForeground(new java.awt.Color(91, 52, 46));
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlCafecito.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(pnlCafecito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIngredientesMouseClicked

        txtId.setText(tablaIngredientes.getValueAt(tablaIngredientes.getSelectedRow(), 0).toString());
        txtNombre.setText(tablaIngredientes.getValueAt(tablaIngredientes.getSelectedRow(), 1).toString());
        txtAbreviacion.setText(tablaIngredientes.getValueAt(tablaIngredientes.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_tablaIngredientesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ingredientes.eliminarIngrediente(Integer.parseInt(txtId.getText()));
        cargarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        Ingredientes ingrediente = new Ingredientes();
        ingrediente.setIdingredientes(Integer.parseInt(txtId.getText()));
        ingrediente.setNombre(txtNombre.getText());
        ingrediente.setAbreviacion(txtAbreviacion.getText());
        ingrediente.setPlatilloList(new ArrayList<Platillo>());

        ingredientes.editarIngrediente(ingrediente);
        cargarTabla();
        limpiarCampos();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Ingredientes ingrediente = new Ingredientes();
        ingrediente.setNombre(txtNombre.getText());
        ingrediente.setAbreviacion(txtAbreviacion.getText());

        ingredientes.registrarIngrediente(ingrediente);
        cargarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        adminMenu = new FmAdminMenu(usuarioActual);
//        adminMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmAdminIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmAdminIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmAdminIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmAdminIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmAdminIngredientes().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("\\images\\icon.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbreviacion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel pnlCafecito;
    private javax.swing.JTable tablaIngredientes;
    private javax.swing.JTextField txtAbreviacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
