/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Entidades.Platillo;
import fachadaLogica.FachadaLogica;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import paneles.codigo.PanelOrden;

/**
 *
 * @author Brenda Bojorquez
 */
public class FrmConfirmarOrden extends javax.swing.JFrame {

    private List<Platillo> platillos;
    private FachadaLogica fachadaLogica;
    private PanelOrden panelOrden;
    
    public FrmConfirmarOrden(List<Platillo> platillos, PanelOrden panelOrden) {
        initComponents();
        this.platillos= platillos;
        fachadaLogica = new FachadaLogica();
        this.panelOrden = panelOrden;
        mostrarPlatillos();
    }

    private void mostrarPlatillos(){
        float total = 0;
        this.setLocationRelativeTo(null);
        setResizable(false);
        pack();
        for (Platillo platillo : platillos) {
            txtPlatillos.append(platillo.toString() + "\n");
            total+=platillo.getCosto()*platillo.getCantidad();
        }
        
        txtPlatillos.append("-------------------------"
                + "\nTotal              $"+total);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCafecito = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlatillos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmar orden");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCafecito.setBackground(new java.awt.Color(226, 207, 169));
        pnlCafecito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmar.setBackground(new java.awt.Color(245, 133, 25));
        btnConfirmar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(91, 52, 46));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        pnlCafecito.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 132, 60));

        txtPlatillos.setEditable(false);
        txtPlatillos.setColumns(20);
        txtPlatillos.setRows(5);
        txtPlatillos.setFocusable(false);
        jScrollPane1.setViewportView(txtPlatillos);

        pnlCafecito.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 590, 220));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 133, 25));
        jLabel1.setText("Verifique que la orden sea correcta");
        pnlCafecito.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 510, -1));

        btnRegresar.setBackground(new java.awt.Color(245, 133, 25));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(91, 52, 46));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlCafecito.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 128, 60));

        getContentPane().add(pnlCafecito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
            fachadaLogica.guardarOrden((ArrayList<Platillo>) platillos);
            JOptionPane.showMessageDialog(this, "Orden guardada", "Confirmación", JOptionPane.PLAIN_MESSAGE);
            panelOrden.clearPlatillos();
            panelOrden.setLastOrdenId();
            this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/icon.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCafecito;
    private javax.swing.JTextArea txtPlatillos;
    // End of variables declaration//GEN-END:variables
}
