/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import vistas.FmPrincipal;

/**
 *
 * @author Diana Jiménez
 */
public class DetalleOrden extends javax.swing.JPanel {

    private FmPrincipal tomarOrden;
    /**
     * Creates new form DetalleOrden
     */
    public DetalleOrden(FmPrincipal fmPrincipal) {
        initComponents();
        setSize(550, 1000);
        this.setLocation(5, 15);
        this.tomarOrden=fmPrincipal;
//        setResizable(false);
//        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblOrden = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(254, 244, 222));
        setMinimumSize(new java.awt.Dimension(785, 1000));
        setPreferredSize(new java.awt.Dimension(550, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblOrden.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblOrden.setText("Orden: 001");
        add(jlblOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(247, 157, 68));
        btnSiguiente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSiguiente.setText("Guardar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 760, 120, 70));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtArea.setRows(5);
        txtArea.setMinimumSize(new java.awt.Dimension(260, 95));
        jScrollPane1.setViewportView(txtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 415, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        //guardarOrden();
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblOrden;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
