/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import vistas.FmPrincipal;
import java.awt.Dimension;
import java.awt.LayoutManager;

/**
 *
 * @author Diana Jiménez
 */
public class DetalleOrden extends javax.swing.JPanel {

    private FmPrincipal tomarOrden;
    private Dimension tamPrincipal;
    private Dimension tamText;
    private Dimension tamPanel;
    /**
     * Creates new form DetalleOrden
     */
    public DetalleOrden(FmPrincipal fmPrincipal) {
        initComponents();
        this.setLocation(0, 0);
        this.tomarOrden=fmPrincipal;
        int ancho = tomarOrden.getWidth()/3;
        int largo = tomarOrden.getHeight();
        tamPrincipal = new Dimension(ancho, largo);
        this.setSize(tamPrincipal);
        
        int anchoPanel = ancho;
        int largoPanel = largo;
//        jPanel1.setSize(anchoPanel, largoPanel);
        tamPanel = new Dimension(anchoPanel, largoPanel);
        pnlCremita.setSize(tamPrincipal);
       // pnlCremita.setPreferredSize(tamPanel);
        
        int ancho2 = anchoPanel;
        int largo2 = largoPanel;
        txtArea.setSize(ancho, largo);
        jScrollPane1.setSize(ancho, largo);
        tamText = new Dimension(ancho, largo);
        jScrollPane1.setPreferredSize(tamText);
        txtArea.setPreferredSize(tamText);
        
//        setResizable(false);
//        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCremita = new javax.swing.JPanel();
        jlblOrden = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(226, 207, 169));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(tamPrincipal);

        pnlCremita.setBackground(new java.awt.Color(254, 244, 222));
        pnlCremita.setPreferredSize(tamPanel);

        jlblOrden.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblOrden.setText("Orden: 001");

        btnSiguiente.setBackground(new java.awt.Color(247, 157, 68));
        btnSiguiente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSiguiente.setText("Guardar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jScrollPane1.setMaximumSize(tamText);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(tamText);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtArea.setRows(5);
        txtArea.setMargin(null);
        txtArea.setMaximumSize(tamText);
        txtArea.setMinimumSize(null);
        txtArea.setName(""); // NOI18N
        txtArea.setPreferredSize(tamText);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout pnlCremitaLayout = new javax.swing.GroupLayout(pnlCremita);
        pnlCremita.setLayout(pnlCremitaLayout);
        pnlCremitaLayout.setHorizontalGroup(
            pnlCremitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCremitaLayout.createSequentialGroup()
                .addGroup(pnlCremitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCremitaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCremitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCremitaLayout.setVerticalGroup(
            pnlCremitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCremitaLayout.createSequentialGroup()
                .addComponent(jlblOrden)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCremita, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlCremita, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        //guardarOrden();
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblOrden;
    private javax.swing.JPanel pnlCremita;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
