/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import vistas.FmPrincipal;
import java.awt.Dimension;

/**
 *
 * @author Diana Jiménez
 */
public class DetalleOrden extends javax.swing.JPanel {

    private FmPrincipal tomarOrden;
    private Dimension tamPrincipal;
    private Dimension tamText;
    private Dimension tamPanel;
    /**
     * Creates new form DetalleOrden
     */
    public DetalleOrden(FmPrincipal fmPrincipal) {
        initComponents();
        this.setLocation(0, 0);
        this.tomarOrden=fmPrincipal;
        int ancho = tomarOrden.getWidth()/4;
        int largo = tomarOrden.getHeight();
        tamPrincipal = new Dimension(ancho, largo);
        setSize(tamPrincipal);
        
        int anchoPanel = ancho - 20;
        int largoPanel = largo - 50;
        jPanel1.setSize(anchoPanel, largoPanel);
        jPanel1.setLocation(10,25);
        tamPanel = new Dimension(anchoPanel, largoPanel);
        
        int ancho2 = anchoPanel/2;
        int largo2 = anchoPanel-btnSiguiente.getHeight();
        txtArea.setSize(largo2, ancho2);
        tamText = new Dimension(ancho2, largo2);
//        setResizable(false);
//        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblOrden = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(226, 207, 169));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(tamPrincipal);

        jPanel1.setBackground(new java.awt.Color(254, 244, 222));
        jPanel1.setPreferredSize(tamPanel);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblOrden.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblOrden.setText("Orden: 001");
        jPanel1.add(jlblOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 0, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(247, 157, 68));
        btnSiguiente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSiguiente.setText("Guardar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 545, 120, 70));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtArea.setRows(5);
        txtArea.setMargin(null);
        txtArea.setMinimumSize(null);
        txtArea.setName(""); // NOI18N
        txtArea.setPreferredSize(tamText);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 280, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        //guardarOrden();
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblOrden;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
